/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package singleton.design.pattern;

public class App {
    public static void main(String[] args) {
        final Class1 cls1 = new Class1();
        final Class2 cls2 = new Class2();

        cls1.doSomething();
        cls2.doSomething();

    }
}
